sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX10_S10_R1_001.fastq.gz --output_folder SX_10
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX11_S11_R1_001.fastq.gz --output_folder SX_11
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX12_S12_R1_001.fastq.gz --output_folder SX_12
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX13_S13_R1_001.fastq.gz --output_folder SX_13
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data --file_name SX14_S14_R1_001.fastq.gz --output_folder SX_14
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX15_S15_R1_001.fastq.gz --output_folder SX_15
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX16_S16_R1_001.fastq.gz --output_folder SX_16
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX17_S17_R1_001.fastq.gz --output_folder SX_17
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX18_S25_R1_001.fastq.gz --output_folder SX_18
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX19_S19_R1_001.fastq.gz --output_folder SX_19
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX1_S1_R1_001.fastq.gz --output_folder SX_1
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX20_S10_R1_001.fastq.gz --output_folder SX_20
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX21_S21_R1_001.fastq.gz --output_folder SX_21
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX22_S22_R1_001.fastq.gz --output_folder SX_22
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX23_S23_R1_001.fastq.gz --output_folder SX_23
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX24_S24_R1_001.fastq.gz --output_folder SX_24
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX25_S25_R1_001.fastq.gz --output_folder SX_25
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX26_S26_R1_001.fastq.gz --output_folder SX_36
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX2_S2_R1_001.fastq.gz --output_folder SX_2
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX3_S3_R1_001.fastq.gz --output_folder SX_3
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX4_S4_R1_001.fastq.gz --output_folder SX_4
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX5_S5_R1_001.fastq.gz --output_folder SX_5
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX6_S6_R1_001.fastq.gz --output_folder SX_6
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX7_S7_R1_001.fastq.gz --output_folder SX_7
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX8_S8_R1_001.fastq.gz --output_folder SX_8
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count' --data_folder ../data/ --file_name SX9_S9_R1_001.fastq.gz --output_folder SX_9
