# htseq count reads only for protein coding genes.

sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-10_S8_R1_001.fastq.gz --output_folder ART_10
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-11_S9_R1_001.fastq.gz --output_folder ART_11
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-12_S10_R1_001.fastq.gz --output_folder ART_12
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-13_S11_R1_001.fastq.gz --output_folder ART_13
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-14_S12_R1_001.fastq.gz --output_folder ART_14
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-15_S13_R1_001.fastq.gz --output_folder ART_15
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-16_S14_R1_001.fastq.gz --output_folder ART_16
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-17_S15_R1_001.fastq.gz --output_folder ART_17
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-18_S16_R1_001.fastq.gz --output_folder ART_18
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-19_S17_R1_001.fastq.gz --output_folder ART_19
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-1_S23_R1_001.fastq.gz --output_folder ART_1
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-20_S18_R1_001.fastq.gz --output_folder ART_20
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-21_S19_R1_001.fastq.gz --output_folder ART_21
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-22_S20_R1_001.fastq.gz --output_folder ART_22
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-23_S21_R1_001.fastq.gz --output_folder ART_23
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-24_S22_R1_001.fastq.gz --output_folder ART_24
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-2_S24_R1_001.fastq.gz --output_folder ART_2
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-3_S1_R1_001.fastq.gz --output_folder ART_3
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-4_S2_R1_001.fastq.gz --output_folder ART_4
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-5_S3_R1_001.fastq.gz --output_folder ART_5
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-6_S4_R1_001.fastq.gz --output_folder ART_6
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-7_S5_R1_001.fastq.gz --output_folder ART_7
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-8_S6_R1_001.fastq.gz --output_folder ART_8
sos run ../lib/170219_bioinformatics_preprocessing_for_Xiao_mRNA_Seq.sos 'gunzip+lqr_removal+mapping+htseq_count_protein_coding' --data_folder ../data/Shuo_Xiao_RNAseq_mouse_batch1/ --file_name ART-9_S7_R1_001.fastq.gz --output_folder ART_9
